### ISSUE TITLE
Erweiterung der exportierten Daten

### ISSUE THREAD

**Issue by s-strasser** [CodeCommerce/dsgvo_userexport#2]
https://github.com/CodeCommerce/dsgvo_userexport/blob/a0d9f9e3af8dfc148edb18ee6a9c4c6d6f00074d/copy_this/modules/codecommerce/dsgvo_userdata/controllers/admin/cc_dsgvo_userdata_export.php#L59

Hier wäre eine Erweiterungsmöglichkeit schön, bei der man nicht die ganze Funktion überschreiben muss, z.B. via einem Array an Callbacks?

**Comment by CodeCommerce** [comment]
Funktion externalDataHook() hinzugefügt in modules/codecommerce/dsgvo_userdata/controllers/admin/cc_dsgvo_userdata_export.php
